# CliArgs
args:
  ip: 127.0.0.1
  port: 8080
  silent: false
  log_level: info
  dns_mode: system
  dns_provider: google
  dns_qtype: ipv4
  http_split_mode: none
  https_split_mode: none
  https_fake_ttl_mode: none
  https_fake_ttl_value: 0
  https_greased_padding: false

# EngineConfig
engine:
  # Размер буфера для чтения HTTP-заголовков и данных (байт).
  buffer_capacity: 2048
  # Лимит конкурентных соединений (защита от исчерпания файловых дескрипторов).
  max_concurrent_connections: 200
  # Максимальное время жизни прокси-сессий (защита от зомби-соединений) (сек).
  max_session_duration_secs: 300
  # Предел неактивности TCP-соединения (сек).
  tcp_idle_timeout_secs: 60
  # Тайм-аут на установку исходящего соединения с DNS сервером (мс).
  dns_connect_timeout_millis: 3000
  # Тайм-аут ожидания завершения при остановке сервиса (graceful shutdown) (сек).
  shutdown_grace_period_secs: 5
  # Настройки TCP Keepalive
  keepalive:
    # Время простоя (idle) перед отправкой первой проверки (сек).
    time_secs: 15
    # Интервал между повторными проверками (если нет ответа) (сек).
    interval_secs: 5
    # Количество неудачных попыток до разрыва соединения.
    retries: 3
  # Настройки фрагментации TLS-ClientHello (диапазоны [min, max]) (при --https-split-mode fragment)
  tls_fragmentation:
    # Jitter для первого фрагмента (мс).
    first_jitter_ms: [1, 5]
    # Jitter для критической зоны SNI (мс).
    chunk_jitter_ms: [1, 5]
    # Смещение (до/после) для критической зоны SNI (байт).
    sni_offset: [1, 5]
    # Диапазон размеров чанков для критической зоны SNI (байт).
    chunk_size: [1, 6]
  # Настройки фрагментации HTTP-headers (диапазоны [min, max]) (при --http-split-mode fragment)
  http_fragmentation:
    # Jitter для первого фрагмента (мс).
    first_jitter_ms: [2, 6]
    # Jitter чанка для последующих данных (мс).
    chunk_jitter_ms: [1, 5]
    # Смещение первой части заголовка (байт).
    first_offset: [1, 5]
    # Диапазон размеров чанков для последующих данных (байт).
    chunk_size: [24, 148]
  # Настройки формирования TLS-ClientHello (при --https-greased-padding true)
  tls_client_hello_shaping:
    # Вероятность использования GREASE вместо обычного Padding (0.0 — 1.0).
    grease_ratio: 0.15
    # Вероятность выбора "легкого" профиля (0.0 - 1.0).
    light_profile_ratio: 0.75
    # Вероятность появления случайного байта в наполнении Padding (0.0 — только нули, 1.0 — только случайные).
    padding_entropy_ratio: 0.15
    # Диапазон добавки (дельты) к размеру исходного TLS-ClientHello для легкого профиля (байт).
    light_client_hello_delta: [194, 520]
    # Диапазон добавки (дельты) к размеру исходного TLS-ClientHello для тяжелого профиля (байт).
    heavy_client_hello_delta: [780, 1850]
